# /plugins/bronze_to_silver/config.py
from typing import Any, Dict

import polars as pl

SCHEMA_CONTRACTS: Dict[str, Dict[str, Any]] = {
    "wells": {
        "is_fact": False,
        "source_date_col": None,
        "columns": {
            "well_id": pl.Int32,
            "name": pl.String,
            "field_name": pl.String,
            "region": pl.String,
            "start_date": pl.Date,
            "operator": pl.String,
            "status": pl.String,
        },
        "primary_key": ["well_id"],
        "foreign_keys": {},
        "time_column": "start_date",
        "dedup_key": ["well_id"],
        "validation_rules": {
            "enums": {
                "status": [
                    "active",
                    "inactive",
                    "maintenance",
                    "decommissioned",
                    "suspended",
                ]
            },
            "ranges": {},
            "custom": [{"rule": "start_date <= current_date", "severity": "HIGH"}],
        },
        "outlier_columns": [],
        "missing_rules": {"operator": {"strategy": "fill_value", "value": "UNKNOWN"}},
    },
    "production": {
        "is_fact": True,
        "source_date_col": "date",
        "columns": {
            "prod_id": pl.Int32,
            "well_id": pl.Int32,
            "date": pl.Date,
            "oil_ton": pl.Float64,
            "gas_m3": pl.Float64,
            "water_m3": pl.Float64,
            "energy_kwh": pl.Float64,
            "downtime_hours": pl.Float64,
            "temperature": pl.Float64,
            "pressure": pl.Float64,
        },
        "primary_key": ["prod_id"],
        "foreign_keys": {"well_id": "wells.well_id"},
        "time_column": "date",
        "dedup_key": ["prod_id", "date"],
        "validation_rules": {
            "enums": {},
            "ranges": {
                "oil_ton": {"min": 0.0},
                "gas_m3": {"min": 0.0},
                "water_m3": {"min": 0.0},
                "energy_kwh": {"min": 0.0},
                "downtime_hours": {"min": 0.0, "max": 24.0},
                "pressure": {"min": 0.0, "max": 1000.0},
                "temperature": {"min": -60.0, "max": 250.0},
            },
            "custom": [],
        },
        "outlier_columns": [
            "oil_ton",
            "gas_m3",
            "water_m3",
            "energy_kwh",
            "temperature",
            "pressure",
        ],
        "missing_rules": {
            "oil_ton": {"strategy": "fill_value", "value": 0.0},
            "gas_m3": {"strategy": "fill_value", "value": 0.0},
            "water_m3": {"strategy": "fill_value", "value": 0.0},
            "energy_kwh": {"strategy": "fill_value", "value": 0.0},
            "downtime_hours": {"strategy": "fill_value", "value": 0.0},
        },
    },
    "well_telemetry": {
        "is_fact": True,
        "source_date_col": "timestamp",
        "columns": {
            "record_id": pl.Int32,
            "well_id": pl.Int32,
            "timestamp": pl.Datetime("us"),
            "pump_speed_rpm": pl.Float64,
            "pump_current": pl.Float64,
            "pressure_in": pl.Float64,
            "pressure_out": pl.Float64,
            "temperature": pl.Float64,
            "vibration": pl.Float64,
            "oil_flow_rate": pl.Float64,
        },
        "primary_key": ["record_id"],
        "foreign_keys": {"well_id": "wells.well_id"},
        "time_column": "timestamp",
        "dedup_key": ["record_id", "timestamp"],
        "validation_rules": {
            "enums": {},
            "ranges": {
                "pump_speed_rpm": {"min": 0.0},
                "vibration": {"min": 0.0},
                "oil_flow_rate": {"min": 0.0},
            },
            "custom": [{"rule": "pressure_out >= pressure_in", "severity": "MEDIUM"}],
        },
        "outlier_columns": [
            "pump_speed_rpm",
            "pump_current",
            "pressure_in",
            "pressure_out",
            "temperature",
            "vibration",
            "oil_flow_rate",
        ],
        "missing_rules": {
            col: {
                "strategy": "forward_fill",
                "partition_by": "well_id",
                "order_by": "timestamp",
            }
            for col in [
                "pump_speed_rpm",
                "pump_current",
                "pressure_in",
                "pressure_out",
                "temperature",
                "vibration",
                "oil_flow_rate",
            ]
        },
    },
    "well_targets": {
        "is_fact": True,
        "source_date_col": "date",
        "columns": {
            "well_id": pl.Int32,
            "date": pl.Date,
            "daily_oil_ton": pl.Float64,
        },
        "foreign_keys": {"well_id": "wells.well_id"},
        "time_column": "date",
        "dedup_key": ["well_id", "date"],
        "validation_rules": {
            "enums": {},
            "ranges": {"daily_oil_ton": {"min": 0.0}},
            "custom": [],
        },
        "outlier_columns": [],
        "missing_rules": {},
    },
    "pumps": {
        "is_fact": False,
        "source_date_col": None,
        "columns": {
            "pump_id": pl.Int32,
            "well_id": pl.Int32,
            "type": pl.String,
            "install_date": pl.Date,
            "manufacturer": pl.String,
            "model": pl.String,
        },
        "primary_key": ["pump_id"],
        "foreign_keys": {"well_id": "wells.well_id"},
        "time_column": "install_date",
        "dedup_key": ["pump_id"],
        "validation_rules": {
            "enums": {},
            "ranges": {},
            "custom": [{"rule": "install_date <= current_date", "severity": "HIGH"}],
        },
        "outlier_columns": [],
        "missing_rules": {
            "manufacturer": {"strategy": "fill_value", "value": "UNKNOWN"},
            "model": {"strategy": "fill_value", "value": "UNKNOWN"},
        },
    },
    "pump_sensors": {
        "is_fact": True,
        "source_date_col": "timestamp",
        "columns": {
            "record_id": pl.Int32,
            "pump_id": pl.Int32,
            "timestamp": pl.Datetime("us"),
            "temperature": pl.Float64,
            "vibration": pl.Float64,
            "current": pl.Float64,
            "rpm": pl.Float64,
            "pressure": pl.Float64,
        },
        "primary_key": ["record_id"],
        "foreign_keys": {"pump_id": "pumps.pump_id"},
        "time_column": "timestamp",
        "dedup_key": ["record_id", "timestamp"],
        "validation_rules": {
            "enums": {},
            "ranges": {
                "vibration": {"min": 0.0},
                "rpm": {"min": 0.0},
                "pressure": {"min": 0.0},
            },
            "custom": [],
        },
        "outlier_columns": ["temperature", "vibration", "current", "rpm", "pressure"],
        "missing_rules": {
            col: {
                "strategy": "forward_fill",
                "partition_by": "pump_id",
                "order_by": "timestamp",
            }
            for col in ["temperature", "vibration", "current", "rpm", "pressure"]
        },
    },
    "pump_failures": {
        "is_fact": True,
        "source_date_col": "failure_date",
        "columns": {
            "failure_id": pl.Int32,
            "pump_id": pl.Int32,
            "failure_date": pl.Datetime("us"),
            "failure_type": pl.String,
            "downtime_hours": pl.Float64,
        },
        "primary_key": ["failure_id"],
        "foreign_keys": {"pump_id": "pumps.pump_id"},
        "time_column": "failure_date",
        "dedup_key": ["failure_id"],
        "validation_rules": {
            "enums": {
                "failure_type": [
                    "electrical",
                    "mechanical",
                    "overheating",
                    "seal_failure",
                    "vibration_alarm",
                    "pressure_loss",
                    "bearing vibration",
                    "bearing_vibration",
                    "electrical fault",
                    "electrical_fault",
                    "unknown",
                ]
            },
            "ranges": {"downtime_hours": {"min": 0.0}},
            "custom": [{"rule": "failure_type is not null", "severity": "HIGH"}],
        },
        "outlier_columns": ["downtime_hours"],
        "missing_rules": {"downtime_hours": {"strategy": "fill_value", "value": 0.0}},
    },
    "deliveries": {
        "is_fact": True,
        "source_date_col": "date",
        "columns": {
            "delivery_id": pl.Int32,
            "date": pl.Date,
            "source": pl.String,
            "destination": pl.String,
            "product_type": pl.String,
            "volume_ton": pl.Float64,
            "cost_usd": pl.Float64,
            "delay_hours": pl.Float64,
            "distance_km": pl.Float64,
            "weather_conditions": pl.String,
            "driver_id": pl.Int32,
            "vehicle_id": pl.Int32,
        },
        "primary_key": ["delivery_id"],
        "foreign_keys": {
            "driver_id": "drivers.driver_id",
            "vehicle_id": "vehicles.vehicle_id",
        },
        "time_column": "date",
        "dedup_key": ["delivery_id"],
        "validation_rules": {
            "enums": {
                "product_type": [
                    "crude_oil",
                    "condensate",
                    "diesel",
                    "drilling_fluids",
                    "gasoline",
                    "kerosene",
                ]
            },
            "ranges": {
                "volume_ton": {"min": 0.0},
                "cost_usd": {"min": 0.0},
                "delay_hours": {"min": 0.0},
                "distance_km": {"min": 0.0001},
            },
            "custom": [],
        },
        "outlier_columns": ["volume_ton", "cost_usd", "delay_hours", "distance_km"],
        "missing_rules": {
            "weather_conditions": {"strategy": "fill_value", "value": "UNKNOWN"}
        },
    },
    "drivers": {
        "is_fact": False,
        "source_date_col": None,
        "columns": {
            "driver_id": pl.Int32,
            "name": pl.String,
            "experience_years": pl.Int32,
            "region": pl.String,
        },
        "primary_key": ["driver_id"],
        "foreign_keys": {},
        "time_column": None,
        "dedup_key": ["driver_id"],
        "validation_rules": {
            "enums": {},
            "ranges": {"experience_years": {"min": 0, "max": 60}},
            "custom": [],
        },
        "outlier_columns": [],
        "missing_rules": {"region": {"strategy": "fill_value", "value": "UNKNOWN"}},
    },
    "vehicles": {
        "is_fact": False,
        "source_date_col": None,
        "columns": {
            "vehicle_id": pl.Int32,
            "plate_number": pl.String,
            "capacity_ton": pl.Float64,
            "fuel_type": pl.String,
        },
        "primary_key": ["vehicle_id"],
        "foreign_keys": {},
        "time_column": None,
        "dedup_key": ["vehicle_id"],
        "validation_rules": {
            "enums": {
                "fuel_type": ["diesel", "gasoline", "electric", "hybrid", "lng", "gas"]
            },
            "ranges": {"capacity_ton": {"min": 0.0001}},
            "custom": [],
        },
        "outlier_columns": ["capacity_ton"],
        "missing_rules": {"fuel_type": {"strategy": "fill_value", "value": "UNKNOWN"}},
    },
    "oil_stations": {
        "is_fact": False,
        "source_date_col": None,
        "columns": {
            "station_id": pl.Int32,
            "station_name": pl.String,
            "latitude": pl.Float64,
            "longitude": pl.Float64,
            "oil_flow_per_day": pl.Float64,
        },
        "primary_key": ["station_id"],
        "foreign_keys": {},
        "time_column": None,
        "dedup_key": ["station_id"],
        "validation_rules": {
            "enums": {},
            "ranges": {
                "latitude": {"min": -90.0, "max": 90.0},
                "longitude": {"min": -180.0, "max": 180.0},
                "oil_flow_per_day": {"min": 0.0},
            },
            "custom": [],
        },
        "outlier_columns": ["oil_flow_per_day"],
        "missing_rules": {"oil_flow_per_day": {"strategy": "fill_value", "value": 0.0}},
    },
}
